struct SysAction {pub sys_action_idi32,
pub src_entity_name Option<String>,
pub src_entity_id Option<String>,
pub action_codeString,
pub sequencei32,
pub next_action_code Option<String>,
pub action_nameString,
pub action_typeString,
pub description Option<String>,
pub class_name Option<String>,
pub method_name Option<String>,
pub next_line_seq_pass Option<i32>,
pub next_line_seq_fail Option<i32>,
pub next_line_seq_onhold Option<i32>,
pub activity_path Option<String>,
pub created_byString,
pub creation_dateDateTime<Utc>,
pub last_updated_byString,
pub last_update_dateDateTime<Utc>,

}